version: "3.8"
services:
  db:
    # CRITICAL CHANGE: Use PostgreSQL Image
    image: postgres:18-alpine
    environment:
      # Use POSTGRES-specific environment variables
      POSTGRES_DB: report_issues
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    volumes:
      # Change volume mount path for Postgres
      - db-data:/var/lib/postgresql/data
    ports:
      # Change port mapping to 5432
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    # Removed unnecessary 'sleep 25' command
    entrypoint: ["java","-jar","/app/app.jar"]
    environment:
      # CRITICAL CHANGE: Update URL to use postgres driver and the container hostname 'db'
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d3k780l6ubrc73do06t0-a.oregon-postgres.render.com:5432/report_issues_mntj?sslmode=require
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: p7jyNRbJ36hPFy7vQ5emos1KCQec3UQf
      APP_ADMIN_USERNAME: admin
      APP_ADMIN_PASSWORD: admin123
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_USERNAME: reportlocalissues@gmail.com
      SPRING_MAIL_PASSWORD: bdnw cepp ionx djao
      APP_EMAIL_ENABLED: "true"
      APP_UPLOAD_DIR: /app/uploads
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

volumes:
  db-data:


#version: "3.8"
#services:
#  db:
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: 12345678
#      MYSQL_DATABASE: report_issues
#      MYSQL_USER: app
#      MYSQL_PASSWORD: secret
#    volumes:
#      - db-data:/var/lib/mysql
#    ports:
#      - "3306:3306"
#
#  app:
#    build: .
#    depends_on:
#      - db
#    command: ["sh", "-c", "sleep 25 && java -jar /app/app.jar"]
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/report_issues?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#      SPRING_DATASOURCE_USERNAME: app
#      SPRING_DATASOURCE_PASSWORD: secret
#      APP_ADMIN_USERNAME: admin
#      APP_ADMIN_PASSWORD: admin123
#      SPRING_MAIL_HOST: smtp.gmail.com
#      SPRING_MAIL_USERNAME: reportlocalissues@gmail.com
#      SPRING_MAIL_PASSWORD: fnku kjdh vozn zwwr
#      APP_EMAIL_ENABLED: "true"
#      APP_UPLOAD_DIR: /app/uploads
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./uploads:/app/uploads
#    restart: unless-stopped
#
#volumes:
#  db-data:
